POST http://localhost:8000/login/
Content-Type: application/json

{"username": "admin", "password":"1234"}

###

GET http://localhost:8000/frequenciaAPI/getFrequencia/Lucas Oliveira/
Content-Type: application/json
Authorization: Token 2c7773c7575c2dc8c955328b0217174e287d5833

###

GET http://localhost:8000/frequenciaAPI/getFrequenciaTurma/diurno2025/2025-01-01
Content-Type: application/json
Authorization: Token 2c7773c7575c2dc8c955328b0217174e287d5833

###

GET http://localhost:8000/frequenciaAPI/getFrequencia/
Content-Type: application/json
Authorization: Token 2c7773c7575c2dc8c955328b0217174e287d5833
