# Generated by Django 5.1.4 on 2025-02-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'ano')},
        ),
    ]
