# Generated by Django 5.1.4 on 2025-02-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulado',
            old_name='quant_questões',
            new_name='quant_questoes',
        ),
    ]
