# Generated by Django 5.1.4 on 2025-02-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0002_rename_quant_questões_simulado_quant_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='simulado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simulado.simulado'),
            preserve_default=False,
        ),
    ]
