# Generated by Django 5.1.4 on 2025-02-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0003_nota_simulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulado',
            name='dia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulado',
            name='mes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='path_gabarito',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='path_respostas',
            field=models.CharField(max_length=10000),
        ),
    ]
