POST http://localhost:8000/login/
Content-Type: application/json

{"username": "test_user_admin", "password":"password"}

###

POST http://localhost:8000/signup/
Content-Type: application/json
Authorization: Token fad6fae02c750b9f06870fbf3eed0390638eb867

{"username": "pfc", "password":"1234", "email":"email@email.com", "role":"student"}

###
# super user, 
# if not created run: python3 manage.py createsuperuser
# enter localhost:8000/admin and login to superuser to set roles munaly

POST http://localhost:8000/login/
Content-Type: application/json

{"username":"admin", "password":"1234"}

###

GET http://localhost:8000/test_token/
Content-Type: application/json
Authorization: Token ca4a495d7c7ea194135aee8ac15814e8bd86692a

{}

###

